In [27]:
import pandas as pd
from ct_schools import schools

In [28]:
wait_list = pd.read_excel("data/Ct Mirror FOI 1-19 - Wait List.xlsx")
wait_list.head()

,Operator,I st Choice School,Total !st ChoiceApps Remaining on WL - Hartford BL,Total !st ChoiceApps Remaining on WL - Hartford RI,Total !st ChoiceApps Remaining on WL - Suburban All,Total 1st ChoiceApps Remaining on WL - Suburban RI,First IO on WL-#ofRI Within Those 10,First20 on WL-#ofRI Within Those 20
0,BPS,Global Experience Magnet,13.0,NaN,7.0,NaN,NaN,NaN
1,BPS,Wintonbury Early Childhood Magnet,0.0,0,186.0,143,8.0,17
2,CREC,Academy of Aerospace and Engineering,96.0,17,650.0,424,6.0,12
3,CREC,Academy of Aerospace and Engineering Elementary,85.0,19,1268.0,868,6.0,13
4,CREC,Academy of Science and Innovation,19.0,NaN,161.0,52,NaN,9

In [29]:
# Let's clean these column names
for c in wait_list.columns: print c

Operator
I st Choice School
Total !st ChoiceApps Remaining on WL - Hartford BL
Total !st ChoiceApps Remaining on WL - Hartford RI
Total !st ChoiceApps Remaining on WL - Suburban All
Total 1st ChoiceApps Remaining on WL - Suburban RI
First IO on WL-#ofRI
Within Those 10
First20 on
WL-#ofRI
Within Those 20

In [30]:
wait_list.columns = ["operator",
                     "school_first_choice",
                     "wait_list_hartford_bl",
                     "wait_list_hartford_ri",
                     "wait_list_sub_all",
                     "wait_list_sub_ri",
                     "first_10_ri",
                     "first_20_ri"
                    ]
wait_list.head()

,operator,school_first_choice,wait_list_hartford_bl,wait_list_hartford_ri,wait_list_sub_all,wait_list_sub_ri,first_10_ri,first_20_ri
0,BPS,Global Experience Magnet,13.0,NaN,7.0,NaN,NaN,NaN
1,BPS,Wintonbury Early Childhood Magnet,0.0,0,186.0,143,8.0,17
2,CREC,Academy of Aerospace and Engineering,96.0,17,650.0,424,6.0,12
3,CREC,Academy of Aerospace and Engineering Elementary,85.0,19,1268.0,868,6.0,13
4,CREC,Academy of Science and Innovation,19.0,NaN,161.0,52,NaN,9

In [31]:
wait_list = wait_list.dropna(subset=["school_first_choice"])

In [32]:
wait_list

,operator,school_first_choice,wait_list_hartford_bl,wait_list_hartford_ri,wait_list_sub_all,wait_list_sub_ri,first_10_ri,first_20_ri
0,BPS,Global Experience Magnet,13.0,NaN,7.0,NaN,NaN,NaN
1,BPS,Wintonbury Early Childhood Magnet,0.0,0,186.0,143,8.0,17
2,CREC,Academy of Aerospace and Engineering,96.0,17,650.0,424,6.0,12
3,CREC,Academy of Aerospace and Engineering Elementary,85.0,19,1268.0,868,6.0,13
4,CREC,Academy of Science and Innovation,19.0,NaN,161.0,52,NaN,9
5,CREC,Ana Grace Academy of the Arts Elementary,19.0,NaN,288.0,148,6.0,9
6,CREC,Discovery Academy,91.0,19,718.0,436,9.0,12
7,CREC,Glastonbury-East Hartford Magnet,42.0,8,1060.0,522,6.0,10
8,CREC,Greater Hartford Academy of the Arts (GHAA) I ...,7.0,0,104.0,38,NaN,NaN
9,CREC,Greater Hartford Academy of the Arts [Full-Day],53.0,NaN,69.0,32,NaN,9
10,CREC,International Magnet School for Global Citizen...,NaN,NaN,786.0,504,9.0,17
11,CREC,MLC for Global and International Studies,22.0,0,26.0,0,0.0,0
12,CREC,Montessori Magnet School (CREC),167.0,II,186.0,74,NaN,7
13,CREC,Museum Academy,0.0,0,205.0,97,6.0,9
14,CREC,Public Safety Academy,18.0,0,9.0,0,0.0,0
15,CREC,Reggio Magnet School of the Arts,NaN,NaN,328.0,213,8.0,15
16,CREC,Two Rivers Magnet Middle School,NaN,0,81.0,13,NaN,8
17,CREC,University of Hartford Magnet School,151.0,NaN,441.0,133,NaN,NaN
18,EHPS,Connecticut 1B Academy,13.0,NaN,117.0,53,6.0,7
19,Goodwin,Connecticut River Academy at Goodwin College,22.0,NaN,40.0,NaN,NaN,NaN
20,Goodwin,Riverside Magnet School at Goodwin College,34.0,NaN,367.0,87,NaN,NaN
21,HPS,Betances Early Reading Lab Magnet School,13.0,0,45.0,25,NaN,8
22,HPS,Betances STEM Magnet School,17.0,NaN,NaN,0,NaN,NaN
23,HPS,Breakthrough II Magnet School,32.0,NaN,15.0,0,0.0,0
24,HPS,"Breakthrough Magnet School, South Campus",144.0,NaN,65.0,JO,0.0,0
25,HPS,Capitol Community College Magnet Academy,0.0,0,NaN,0,0.0,0
26,HPS,Capital Prep - Lower School,210.0,NaN,247.0,NaN,0.0,0
27,HPS,Capital Prep - Upper School,64.0,0,45.0,NaN,0.0,0
28,HPS,Classical Magnet School,45.0,NaN,NaN,0,0.0,0
29,HPS,Environmental Sciences @ Mary M. Hooker,69.0,7,105.0,47,NaN,8
30,HPS,Great Path Academy,NaN,0,32.0,8,NaN,NaN
31,HPS,Hartford Magnet Trinity College Academy- (Grad...,185.0,7,78.0,14,0.0,NaN
32,HPS,Hartford Magnet Trinity College Academy- (Grad...,NaN,0,NaN,0,0.0,0
33,HPS,Hartford PreKindergarten Magnet,15.0,0,27.0,8,0.0,NaN
34,HPS,Montessori Magnet at Moylan,48.0,NaN,39.0,15,0.0,NaN
35,HPS,Montessori Magnet at Annie Fisher,59.0,NaN,136.0,70,NaN,II
36,HPS,Noah Webster MicroSociety Magnet,113.0,NaN,72.0,12,0.0,NaN
37,HPS,Pathways Academy of Technology and Design,49.0,NaN,37.0,7,0.0,NaN
38,HPS,R.J. Kinsella Magnet School of the Performing ...,172.0,6,127.0,16,NaN,0
39,HPS,Sport and Medical Sciences Academy,138.0,16,48.0,12,NaN,NaN
40,HPS,STEM Magnet School at Annie Fisher,35.0,6,155.0,95,NaN,JO
41,HPS,University High School of Science and Engineering,20.0,7,37.0,JO,NaN,NaN

In [33]:
wait_list.dtypes

operator                  object
school_first_choice       object
wait_list_hartford_bl    float64
wait_list_hartford_ri     object
wait_list_sub_all        float64
wait_list_sub_ri          object
first_10_ri              float64
first_20_ri               object
dtype: object

In [34]:
# Get the best guesses for school names
# and then list them in order of lowest fuzzy ratio (worst match)
# to highest ratio (best match) so we can individually examine
# some of the more questionable matches

wait_list["name_guess"] = wait_list["school_first_choice"].apply(lambda x: schools.school_by_name(x, closest=True).iloc[0]["School Name"])
wait_list["fuzz_ratio"] = wait_list["school_first_choice"].apply(lambda x: schools.school_by_name(x, closest=True).iloc[0]["FUZZ_RATIO"])
wait_list["lat"] = wait_list["school_first_choice"].apply(lambda x: schools.school_by_name(x, closest=True).iloc[0]["lat"])
wait_list["lng"] = wait_list["school_first_choice"].apply(lambda x: schools.school_by_name(x, closest=True).iloc[0]["lng"])
wait_list["lat_lng"] = wait_list["school_first_choice"].apply(lambda x: schools.school_by_name(x, closest=True).iloc[0]["lat_lng"])

In [35]:
wait_list[["school_first_choice","name_guess","fuzz_ratio"]].sort_values(by="fuzz_ratio")

,school_first_choice,name_guess,fuzz_ratio
40,STEM Magnet School at Annie Fisher,STEM Magnet at Fisher School,68
26,Capital Prep - Lower School,Capital Preparatory Magnet School,69
27,Capital Prep - Upper School,Capital Preparatory Magnet School,70
19,Connecticut River Academy at Goodwin College,Connecticut River Academy,72
11,MLC for Global and International Studies,Metropolitan Learning Center for Global and In...,76
29,Environmental Sciences @ Mary M. Hooker,Environmental Sciences Magnet at Hooker School,78
9,Greater Hartford Academy of the Arts [Full-Day],Greater Hartford Academy of the Arts Magnet Mi...,78
24,"Breakthrough Magnet School, South Campus",Breakthrough Magnet School,79
36,Noah Webster MicroSociety Magnet,Webster Micro Society Magnet School,81
35,Montessori Magnet at Annie Fisher,Montessori Magnet at Fisher School,81
30,Great Path Academy,Great Path Academy at MCC,84
31,Hartford Magnet Trinity College Academy- (Grad...,Hartford Magnet Trinity College Academy,84
32,Hartford Magnet Trinity College Academy- (Grad...,Hartford Magnet Trinity College Academy,85
0,Global Experience Magnet,Global Experience Magnet School,87
12,Montessori Magnet School (CREC),Montessori Magnet School,87
7,Glastonbury-East Hartford Magnet,Glastonbury/East Hartford Magnet School,87
8,Greater Hartford Academy of the Arts (GHAA) I ...,Greater Hartford Academy of the Arts Magnet Mi...,88
34,Montessori Magnet at Moylan,Montessori Magnet at Moylan School,89
33,Hartford PreKindergarten Magnet,Hartford PreKindergarten Magnet School,90
38,R.J. Kinsella Magnet School of the Performing ...,Kinsella Magnet School of Performing Arts,90
1,Wintonbury Early Childhood Magnet,Wintonbury Early Childhood Magnet School,90
5,Ana Grace Academy of the Arts Elementary,Ana Grace Academy of the Arts Elementary School,92
18,Connecticut 1B Academy,Connecticut IB Academy,95
25,Capitol Community College Magnet Academy,Capital Community College Magnet Academy,98
39,Sport and Medical Sciences Academy,Sports and Medical Sciences Academy,99
37,Pathways Academy of Technology and Design,Pathways Academy of Technology and Design,100
28,Classical Magnet School,Classical Magnet School,100
20,Riverside Magnet School at Goodwin College,Riverside Magnet School at Goodwin College,100
22,Betances STEM Magnet School,Betances STEM Magnet School,100
21,Betances Early Reading Lab Magnet School,Betances Early Reading Lab Magnet School,100
17,University of Hartford Magnet School,University of Hartford Magnet School,100
16,Two Rivers Magnet Middle School,Two Rivers Magnet Middle School,100
15,Reggio Magnet School of the Arts,Reggio Magnet School of the Arts,100
14,Public Safety Academy,Public Safety Academy,100
13,Museum Academy,Museum Academy,100
10,International Magnet School for Global Citizen...,International Magnet School for Global Citizen...,100
6,Discovery Academy,Discovery Academy,100
4,Academy of Science and Innovation,Academy of Science and Innovation,100
3,Academy of Aerospace and Engineering Elementary,Academy of Aerospace and Engineering Elementary,100
2,Academy of Aerospace and Engineering,Academy of Aerospace and Engineering,100
23,Breakthrough II Magnet School,Breakthrough II Magnet School,100
41,University High School of Science and Engineering,University High School of Science and Engineering,100

In [36]:
# Most of the above look good 
# let's take a closer look at a few

schools.school_by_name("Capital Prep")

,Unnamed: 0,School Name,Organization Type,Organization Code,Location 1,Zipcode,Phone,PreKindergarten,Kindergarten,Grade 1,...,Grade 9,Grade 10,Grade 11,Grade 12,Student Open Date,Interdistrict Magnet,lat_lng,lat,lng,FUZZ_RATIO
628,628,Capital Preparatory Magnet School,Public Schools,646911,"1304 Main Street\nHartford, CT 06103\n(41.7723...",06103,860-695-9800,1,1,1,...,1,1,1,1,01Jul2005 0:00:00.000,1.0,"('41.772344', ' -72.67604')",41.772344,-72.67604,53

In [37]:
wait_list.sort_values(by="fuzz_ratio",ascending=True)[["school_first_choice","name_guess","lat","lng","fuzz_ratio","lat_lng"]]

,school_first_choice,name_guess,lat,lng,fuzz_ratio,lat_lng
40,STEM Magnet School at Annie Fisher,STEM Magnet at Fisher School,41.791455,-72.708169,68,"('41.791455', ' -72.708169')"
26,Capital Prep - Lower School,Capital Preparatory Magnet School,41.772344,-72.676040,69,"('41.772344', ' -72.67604')"
27,Capital Prep - Upper School,Capital Preparatory Magnet School,41.772344,-72.676040,70,"('41.772344', ' -72.67604')"
19,Connecticut River Academy at Goodwin College,Connecticut River Academy,NaN,NaN,72,NaN
11,MLC for Global and International Studies,Metropolitan Learning Center for Global and In...,41.871899,-72.725367,76,"('41.871899', ' -72.725367')"
29,Environmental Sciences @ Mary M. Hooker,Environmental Sciences Magnet at Hooker School,41.741112,-72.700528,78,"('41.741112', ' -72.700528')"
9,Greater Hartford Academy of the Arts [Full-Day],Greater Hartford Academy of the Arts Magnet Mi...,41.755448,-72.664054,78,"('41.755448', ' -72.664054')"
24,"Breakthrough Magnet School, South Campus",Breakthrough Magnet School,41.747153,-72.706594,79,"('41.747153', ' -72.706594')"
36,Noah Webster MicroSociety Magnet,Webster Micro Society Magnet School,41.768894,-72.712253,81,"('41.768894', ' -72.712253')"
35,Montessori Magnet at Annie Fisher,Montessori Magnet at Fisher School,41.791455,-72.708169,81,"('41.791455', ' -72.708169')"
30,Great Path Academy,Great Path Academy at MCC,41.764578,-72.554719,84,"('41.764578', ' -72.554719')"
31,Hartford Magnet Trinity College Academy- (Grad...,Hartford Magnet Trinity College Academy,41.751262,-72.686491,84,"('41.751262', ' -72.686491')"
32,Hartford Magnet Trinity College Academy- (Grad...,Hartford Magnet Trinity College Academy,41.751262,-72.686491,85,"('41.751262', ' -72.686491')"
0,Global Experience Magnet,Global Experience Magnet School,41.869999,-72.735206,87,"('41.869999', ' -72.735206')"
12,Montessori Magnet School (CREC),Montessori Magnet School,41.749562,-72.687108,87,"('41.749562', ' -72.687108')"
7,Glastonbury-East Hartford Magnet,Glastonbury/East Hartford Magnet School,41.706216,-72.594014,87,"('41.706216', ' -72.594014')"
8,Greater Hartford Academy of the Arts (GHAA) I ...,Greater Hartford Academy of the Arts Magnet Mi...,41.755448,-72.664054,88,"('41.755448', ' -72.664054')"
34,Montessori Magnet at Moylan,Montessori Magnet at Moylan School,41.746325,-72.698660,89,"('41.746325', ' -72.69866')"
33,Hartford PreKindergarten Magnet,Hartford PreKindergarten Magnet School,41.791308,-72.701776,90,"('41.791308', ' -72.701776')"
38,R.J. Kinsella Magnet School of the Performing ...,Kinsella Magnet School of Performing Arts,41.755051,-72.664936,90,"('41.755051', ' -72.664936')"
1,Wintonbury Early Childhood Magnet,Wintonbury Early Childhood Magnet School,41.838481,-72.746492,90,"('41.838481', ' -72.746492')"
5,Ana Grace Academy of the Arts Elementary,Ana Grace Academy of the Arts Elementary School,41.807617,-72.836212,92,"('41.807617', ' -72.836212')"
18,Connecticut 1B Academy,Connecticut IB Academy,41.752560,-72.604839,95,"('41.75256', ' -72.604839')"
25,Capitol Community College Magnet Academy,Capital Community College Magnet Academy,41.768360,-72.673045,98,"('41.76836', ' -72.673045')"
39,Sport and Medical Sciences Academy,Sports and Medical Sciences Academy,41.752365,-72.660526,99,"('41.752365', ' -72.660526')"
37,Pathways Academy of Technology and Design,Pathways Academy of Technology and Design,41.740864,-72.634535,100,"('41.740864', ' -72.634535')"
28,Classical Magnet School,Classical Magnet School,41.772855,-72.700469,100,"('41.772855', ' -72.700469')"
20,Riverside Magnet School at Goodwin College,Riverside Magnet School at Goodwin College,41.745141,-72.639556,100,"('41.745141', ' -72.639556')"
22,Betances STEM Magnet School,Betances STEM Magnet School,41.739804,-72.671781,100,"('41.739804', ' -72.671781')"
21,Betances Early Reading Lab Magnet School,Betances Early Reading Lab Magnet School,41.759238,-72.672397,100,"('41.759238', ' -72.672397')"
17,University of Hartford Magnet School,University of Hartford Magnet School,NaN,NaN,100,NaN
16,Two Rivers Magnet Middle School,Two Rivers Magnet Middle School,41.759392,-72.656659,100,"('41.759392', ' -72.656659')"
15,Reggio Magnet School of the Arts,Reggio Magnet School of the Arts,41.800895,-72.819030,100,"('41.800895', ' -72.81903')"
14,Public Safety Academy,Public Safety Academy,41.948744,-72.602053,100,"('41.948744', ' -72.602053')"
13,Museum Academy,Museum Academy,41.852367,-72.666776,100,"('41.852367', ' -72.666776')"
10,International Magnet School for Global Citizen...,International Magnet School for Global Citizen...,41.806542,-72.595282,100,"('41.806542', ' -72.595282')"
6,Discovery Academy,Discovery Academy,41.719249,-72.675089,100,"('41.719249', ' -72.675089')"
4,Academy of Science and Innovation,Academy of Science and Innovation,41.683155,-72.809510,100,"('41.683155', ' -72.80951')"
3,Academy of Aerospace and Engineering Elementary,Academy of Aerospace and Engineering Elementary,41.643315,-72.663277,100,"('41.643315', ' -72.663277')"
2,Academy of Aerospace and Engineering,Academy of Aerospace and Engineering,41.896106,-72.652093,100,"('41.896106', ' -72.652093')"
23,Breakthrough II Magnet School,Breakthrough II Magnet School,41.804787,-72.704285,100,"('41.804787', ' -72.704285')"
41,University High School of Science and Engineering,University High School of Science and Engineering,41.797834,-72.709685,100,"('41.797834', ' -72.709685')"

In [38]:
wait_list[(wait_list["lat"].isnull()) | (wait_list["lng"].isnull())]

,operator,school_first_choice,wait_list_hartford_bl,wait_list_hartford_ri,wait_list_sub_all,wait_list_sub_ri,first_10_ri,first_20_ri,name_guess,fuzz_ratio,lat,lng,lat_lng
17,CREC,University of Hartford Magnet School,151.0,NaN,441.0,133,NaN,NaN,University of Hartford Magnet School,100,NaN,NaN,NaN
19,Goodwin,Connecticut River Academy at Goodwin College,22.0,NaN,40.0,NaN,NaN,NaN,Connecticut River Academy,72,NaN,NaN,NaN